### ISSUE TITLE
Deploy to azure currently failing

### ISSUE THREAD

**Issue by colinbull** [Sitefinity/azure-sample-app#2]
The deployment to azure is currently failing, using the deploy to azure button below. 

I have attached the logs below, of the error. 

It looks like a nuget package `Progress.Sitefinity.IdentityServer3.AccessTokenValidation` 1.3.0 is missing. 

@nikydobrev @TelerikAdminTeam 

[logs.txt](https://github.com/Sitefinity/azure-sample-app/files/2836370/logs.txt)

**Comment by nikydobrev** [comment]
Hi @colinbull, I've just made a successful deployment, using the deploy to azure button. Can you please check on your side once again? Please make sure you are using master branch.

**Comment by colinbull** [comment]
Humm, this failure seems to be intermittent, but it is the same. Error each time it fails. Just to confirm I'm definitely on the master branch 

![image](https://user-images.githubusercontent.com/585546/52351494-c9898b80-2a22-11e9-98f7-84e571a7abe0.png)

**Comment by colinbull** [comment]
Ok, seems to be working now I'm going to close this and put it down to nuget oddness.
